"""In-process unit tests for the APP_SECRET_KEY hardening (v2.1036.0).

`app.config._resolve_secret_key` decides the session-signing key: a strong
operator value is used verbatim; a blank / placeholder / too-short value is
auto-replaced with a strong random ephemeral key (or hard-fails under
APP_SECRET_KEY_STRICT). These run in-process — no container / HTTP needed.
"""
from __future__ import annotations

import pytest

from app.config import _MIN_SECRET_KEY_LEN, _resolve_secret_key


def test_strong_key_used_verbatim(monkeypatch):
    strong = "s3cure-" + "x" * 40
    monkeypatch.setenv("APP_SECRET_KEY", strong)
    monkeypatch.delenv("APP_SECRET_KEY_STRICT", raising=False)
    assert _resolve_secret_key() == strong


@pytest.mark.parametrize("weak", ["", "change-me", "CHANGE_ME_TO_A_LONG_RANDOM_STRING", "short"])
def test_weak_key_autogenerated(monkeypatch, weak):
    """A weak/blank/placeholder/short key is replaced by a strong random one
    (never returned as-is), so the app is never trivially forgeable."""
    monkeypatch.setenv("APP_SECRET_KEY", weak)
    monkeypatch.delenv("APP_SECRET_KEY_STRICT", raising=False)
    resolved = _resolve_secret_key()
    assert resolved != weak
    assert resolved not in ("", "change-me", "CHANGE_ME_TO_A_LONG_RANDOM_STRING")
    assert len(resolved) >= _MIN_SECRET_KEY_LEN
    # Two calls generate distinct random keys (proves it's freshly generated).
    assert _resolve_secret_key() != resolved


def test_unset_key_autogenerated(monkeypatch):
    monkeypatch.delenv("APP_SECRET_KEY", raising=False)
    monkeypatch.delenv("APP_SECRET_KEY_STRICT", raising=False)
    resolved = _resolve_secret_key()
    assert len(resolved) >= _MIN_SECRET_KEY_LEN


def test_strict_mode_hard_fails_on_weak(monkeypatch):
    monkeypatch.setenv("APP_SECRET_KEY", "")
    monkeypatch.setenv("APP_SECRET_KEY_STRICT", "true")
    with pytest.raises(RuntimeError):
        _resolve_secret_key()


def test_strict_mode_allows_strong_key(monkeypatch):
    strong = "prod-" + "y" * 48
    monkeypatch.setenv("APP_SECRET_KEY", strong)
    monkeypatch.setenv("APP_SECRET_KEY_STRICT", "true")
    assert _resolve_secret_key() == strong
