#!/usr/bin/env python3
"""Build the shipped SRD content library by pulling from Open5e.

This is an INITIAL-BOOTSTRAP tool. The generated files live at
``app/data/local/dnd5e/<type>/<slug>.json`` and are committed to git as
part of the image.

⚠  RE-RUNNING OVERWRITES CURATED DATA — DO NOT BLIND-REGENERATE. ⚠

Since the initial bootstrap, the shipped spell JSONs have been curated
well beyond what this script produces. ``_enrich_cast_action`` emits only
9 basic action fields (damage / damage_type / save_ability / healing /
aoe_targets / attack_roll + id/name/desc); the live files additionally
carry hand-/migration-curated fields this script does NOT derive, e.g.:

  - ``actions[].area`` — AoE shape + size (27 spells). Dropping these
    breaks ``_extract_aoe_area``, AoE placement, and the persistent-AoE
    enter/start-of-turn trigger (docs/plans/aoe-enter-trigger.md).
  - ``upcast`` / ``damage_per_slot`` / ``damage_scaling`` — higher-level
    scaling. Dropping these breaks every ``test_cast_*_upcast``.
  - ``min_level`` / ``category`` / ``cost`` / ``resource_key`` /
    ``active_toggle`` / ``reroll_trigger`` / ``transform_picker`` — action
    gating consumed across the cast paths.

A plain re-run (``os.replace`` overwrites each file wholesale — there is
no merge) silently discards all of the above. The harness will catch it
(``test_spell_catalog_aoe`` gates the 27 AoE shapes; the upcast suites
gate scaling), but don't rely on that — if you must refresh from upstream,
write to a SCRATCH directory (point ``DEST_ROOT`` elsewhere or ``--dry-run``
+ a temp copy), DIFF against the live files, and merge only the genuinely
new upstream changes by hand. The per-field heuristics here (notably
``concentration``, fixed v2.568.1) are also weaker than the curated data.

Run this once when standing up the file-based content framework.

Usage
-----
    python scripts/build_srd_content.py [--type spells,monsters,...] [--dry-run]

By default every content type is rebuilt. Pass ``--type`` with a comma list
to limit (useful when re-running a single category after upstream changes).

What gets written
-----------------
For each content type the script:

1. Paginates through the matching Open5e v1 endpoint.
2. Transforms each upstream record into the per-type Pydantic schema in
   ``app/content_schemas.py``.
3. Best-effort enriches ``actions: list[Action]`` from regex-extracted
   damage / save / healing / attack-roll cues so shipped content has working
   button-gating fields on the character sheet without manual authoring.
4. Validates the result, then writes ``<slug>.json`` (atomically).

Records that fail validation are logged + skipped; the file is not written.
The script prints a per-type summary at the end.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import time
import urllib.request

# Force utf-8 stdout so spell/monster names with non-ASCII characters print
# cleanly on Windows consoles (cp1252 by default).
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Allow ``python scripts/build_srd_content.py`` from the repo root by adding
# the project root to sys.path so ``from app.content_schemas import ...`` works.
_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from app.content_schemas import (   # noqa: E402  (after sys.path tweak)
    Background, ClassFeature, Condition, Feat, Item, Monster, Race, Spell, SubclassFeature,
)

# ── Config ───────────────────────────────────────────────────────────────────
OPEN5E_BASE = "https://api.open5e.com/v1"
DEST_ROOT = _REPO_ROOT / "app" / "data" / "local" / "dnd5e"
ATTRIBUTION = (
    "Adapted from the D&D 5e SRD 5.1 by Wizards of the Coast (CC BY 4.0 / "
    "OGL 1.0a), via the Open5e API (open5e.com, CC BY 4.0). Generated by "
    "scripts/build_srd_content.py. Mechanical summaries are rephrased, not "
    "verbatim. See CREDITS.md."
)
HTTP_HEADERS = {"User-Agent": "SimpleVTT/2.0 (SRD content builder)"}
HTTP_TIMEOUT = 30

# Open5e mirrors many CC-BY / OGL 5e sources. By default we ship only the
# WotC SRD baseline (document__slug == "wotc-srd") because that's the
# perimeter the rest of the codebase's _attribution field already cites and
# the safest license posture for redistribution. ``--include-all`` widens the
# filter to every Open5e document (Tasha's, MCDM, Kobold Press, etc.) for
# operators who have separately verified the licensing.
SRD_DOCUMENT_SLUG = "wotc-srd"

# Windows forbids these characters in filenames; macOS/Linux accept some of
# them but we sanitize uniformly so the repo stays cross-platform.
_INVALID_FS_CHARS = set('<>:"/\\|?*')


def _sanitize_slug(slug: str) -> str:
    """Lowercase the slug, replace any filesystem-hostile chars with hyphens,
    and collapse repeats. Returns an empty string if nothing usable remains
    (caller skips the record)."""
    s = (slug or "").strip().lower()
    out = []
    for c in s:
        if c.isalnum() or c == "-":
            out.append(c)
        elif c in _INVALID_FS_CHARS or c == ":":
            out.append("-")
        # everything else (spaces, dots, punctuation) becomes "-"
        else:
            out.append("-")
    cleaned = re.sub(r"-+", "-", "".join(out)).strip("-")
    return cleaned


# ── HTTP ─────────────────────────────────────────────────────────────────────
def fetch_all(endpoint: str, *, limit: int = 100) -> list[dict]:
    """Paginate through an Open5e v1 endpoint and return every record."""
    results: list[dict] = []
    url: str | None = f"{OPEN5E_BASE}/{endpoint}/?limit={limit}"
    while url:
        print(f"    GET {url}", end="", flush=True)
        req = urllib.request.Request(url, headers=HTTP_HEADERS)
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT) as r:
            data = json.loads(r.read())
        batch = data.get("results", [])
        results.extend(batch)
        print(f"  -> {len(batch)} records (total {len(results)})")
        url = data.get("next")
        if url:
            time.sleep(0.2)   # courtesy delay between pages
    return results


# ── Regex enrichment helpers ─────────────────────────────────────────────────
_DICE_RE = re.compile(r"(\d+d\d+(?:\s*[+-]\s*\d+)?)", re.I)
_SAVE_RE = re.compile(
    r"\b(strength|dexterity|constitution|intelligence|wisdom|charisma)\s+saving\s+throw",
    re.I,
)
_DAMAGE_TYPE_RE = re.compile(
    # Allow `(` and `)` around the dice expression so monster lines like
    # `Hit: 5 (1d6 + 2) slashing damage` still match cleanly.
    r"(\d+d\d+(?:\s*[+-]\s*\d+)?)[\s)]+(acid|bludgeoning|cold|fire|force|lightning|"
    r"necrotic|piercing|poison|psychic|radiant|slashing|thunder)\s+damage",
    re.I,
)
_HEALING_RE = re.compile(
    r"(?:regain|restore|heal)s?\s+(\d+d\d+(?:\s*[+-]\s*\d+)?)\s+hit\s+points",
    re.I,
)
_AOE_RE = re.compile(
    r"up\s+to\s+(\d+)\s+(?:creatures?|targets?|willing\s+creatures?)",
    re.I,
)
_ATTACK_RE = re.compile(r"\b(?:ranged|melee)\s+spell\s+attack\b", re.I)
_SAVE_SHORT = {"strength": "str", "dexterity": "dex", "constitution": "con",
               "intelligence": "int", "wisdom": "wis", "charisma": "cha"}


def _strip_md(text: str) -> str:
    return re.sub(r"[*_#`]+", "", text or "").replace("|", ",").replace("\n", " ").strip()


def _enrich_cast_action(spell: dict, desc: str) -> dict:
    """Build the default cast Action for a spell from regex-extracted cues."""
    dmg_m = _DAMAGE_TYPE_RE.search(desc)
    damage = dmg_m.group(1).replace(" ", "") if dmg_m else ""
    damage_type = dmg_m.group(2).lower() if dmg_m else ""

    save_m = _SAVE_RE.search(desc)
    save_ability = _SAVE_SHORT.get(save_m.group(1).lower(), "") if save_m else ""

    healing = ""
    aoe_targets = 1
    if not damage:
        heal_m = _HEALING_RE.search(desc)
        if not heal_m:
            # Looser fallback: just look for "<dice> hit points"
            heal_m = re.search(r"(\d+d\d+(?:\s*[+-]\s*\d+)?)\s+hit\s+points", desc, re.I)
        if heal_m:
            healing = heal_m.group(1).replace(" ", "")
            aoe_m = _AOE_RE.search(desc)
            aoe_targets = int(aoe_m.group(1)) if aoe_m else 1

    attack_roll = bool(_ATTACK_RE.search(desc))

    return {
        "id": "cast",
        "name": "Cast",
        "desc": "",
        "damage": damage,
        "damage_type": damage_type,
        "save_ability": save_ability,
        "healing": healing,
        "aoe_targets": aoe_targets,
        "attack_roll": attack_roll,
    }


# ── Per-type transformers ────────────────────────────────────────────────────
def transform_spell(up: dict) -> dict:
    desc = _strip_md(up.get("desc", ""))
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "level_int": up.get("level_int", up.get("spell_level", 0)),
        "school": up.get("school", "") or "",
        "spell_lists": up.get("spell_lists") or [],
        "casting_time": up.get("casting_time", "") or "",
        "range": up.get("range", "") or "",
        "duration": up.get("duration", "") or "",
        "components": up.get("components", "") or "",
        "desc": desc,
        "higher_level": up.get("higher_level", "") or "",
        "ritual": (up.get("ritual") or "").strip().lower() in ("yes", "true", "1"),
        # Concentration: Open5e's `concentration` flag ("yes"/"no") is the
        # authority; fall back to the duration string. The older heuristic
        # ("concentration" in duration) silently missed every spell whose
        # duration is phrased "Up to N …" (the common form) with the flag in
        # a separate field — mis-flagging ~125 SRD spells as non-concentration
        # (fixed v2.568.1). "Up to …" is 5e's canonical concentration phrasing,
        # so it's a reliable fallback and matches the runtime's own
        # `_is_concentration` check.
        "concentration": (
            (up.get("concentration") or "").strip().lower() in ("yes", "true", "1")
            or "concentration" in (up.get("duration") or "").lower()
            or (up.get("duration") or "").strip().lower().startswith("up to")
        ),
        "actions": [_enrich_cast_action(up, desc)],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_monster_action(entry: dict, category: str) -> dict:
    """Convert one monster action/reaction/special_ability/legendary_action entry."""
    name = (entry.get("name") or "").strip()
    desc = _strip_md(entry.get("desc") or "")
    dmg_m = _DAMAGE_TYPE_RE.search(desc)
    save_m = _SAVE_RE.search(desc)
    attack = bool(re.search(r"\bAttack:|to hit", desc, re.I))
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or f"unnamed-{category}"
    return {
        "id": slug,
        "name": name,
        "desc": desc,
        "category": category,
        "damage": (dmg_m.group(1).replace(" ", "") if dmg_m else ""),
        "damage_type": (dmg_m.group(2).lower() if dmg_m else ""),
        "save_ability": (_SAVE_SHORT.get(save_m.group(1).lower(), "") if save_m else ""),
        "attack_roll": attack,
    }


def transform_monster(up: dict) -> dict:
    actions: list[dict] = []
    for entry in (up.get("actions") or []):
        if isinstance(entry, dict):
            actions.append(transform_monster_action(entry, "action"))
    for entry in (up.get("reactions") or []):
        if isinstance(entry, dict):
            actions.append(transform_monster_action(entry, "reaction"))
    for entry in (up.get("special_abilities") or []):
        if isinstance(entry, dict):
            actions.append(transform_monster_action(entry, "special_ability"))
    for entry in (up.get("legendary_actions") or []):
        if isinstance(entry, dict):
            actions.append(transform_monster_action(entry, "legendary_action"))

    speed = up.get("speed") or {}
    if not isinstance(speed, dict):
        speed = {"walk": speed}
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "size": up.get("size", "Medium"),
        "type": up.get("type", "humanoid"),
        "alignment": up.get("alignment", "unaligned"),
        "armor_class": up.get("armor_class", 10),
        "armor_desc": up.get("armor_desc", "") or "",
        "hit_points": up.get("hit_points", 1),
        "hit_dice": up.get("hit_dice", "") or "",
        "speed": speed,
        "strength": up.get("strength", 10),
        "dexterity": up.get("dexterity", 10),
        "constitution": up.get("constitution", 10),
        "intelligence": up.get("intelligence", 10),
        "wisdom": up.get("wisdom", 10),
        "charisma": up.get("charisma", 10),
        "damage_vulnerabilities": up.get("damage_vulnerabilities", "") or "",
        "damage_resistances": up.get("damage_resistances", "") or "",
        "damage_immunities": up.get("damage_immunities", "") or "",
        "condition_immunities": up.get("condition_immunities", "") or "",
        "senses": up.get("senses", "") or "",
        "languages": up.get("languages", "") or "",
        "challenge_rating": str(up.get("challenge_rating", "0")),
        "actions": actions,
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_feat(up: dict) -> dict:
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "prerequisite": up.get("prerequisite", "") or "",
        "desc": _strip_md(up.get("desc") or up.get("effects_desc") or ""),
        "actions": [],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_background(up: dict) -> dict:
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "skill_proficiencies": up.get("skill_proficiencies", "") or "",
        "tool_proficiencies": up.get("tool_proficiencies", "") or "",
        "languages": up.get("languages", "") or "",
        "equipment": up.get("equipment", "") or "",
        "feature_name": up.get("feature", "") or "",
        "feature_desc": _strip_md(up.get("feature_desc", "") or ""),
        "suggested_characteristics": up.get("suggested_characteristics", "") or "",
        "actions": [],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_condition(up: dict) -> dict:
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "desc": _strip_md(up.get("desc") or ""),
        "actions": [{
            "id": "effect",
            "name": up.get("name", ""),
            "desc": _strip_md(up.get("desc") or "")[:300],
            "category": "passive",
        }],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_magicitem(up: dict) -> dict:
    """Open5e magic items lack structured charge / damage fields, so we ship
    them as `type='magic'` with empty actions. GMs can extend via the homebrew
    UI to add specific Action entries."""
    return {
        "slug": up.get("slug", ""),
        "name": up.get("name", ""),
        "type": "magic",
        "rarity": (up.get("rarity") or "common").lower(),
        "attunement": bool(up.get("requires_attunement") and
                           (up.get("requires_attunement") or "").lower() not in ("", "no")),
        "weight": "",
        "cost": "",
        "desc": _strip_md(up.get("desc") or ""),
        "properties": {"category": up.get("type", "") or ""},
        "actions": [],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_weapon(up: dict) -> dict:
    props = {
        "damage": (up.get("damage_dice") or "") + (
            f" {up.get('damage_type','')}" if up.get("damage_type") else ""
        ),
        "category": up.get("category", "") or "",
        "properties": up.get("properties") or [],
    }
    return {
        "slug": up.get("key") or up.get("slug") or up.get("name", "").lower().replace(" ", "-"),
        "name": up.get("name", ""),
        "type": "weapon",
        "rarity": "common",
        "attunement": False,
        "weight": str(up.get("weight", "")) + (" lb" if up.get("weight") else ""),
        "cost": str(up.get("cost", "")) or "",
        "desc": "",
        "properties": props,
        "actions": [],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


def transform_armor(up: dict) -> dict:
    return {
        "slug": up.get("key") or up.get("slug") or up.get("name", "").lower().replace(" ", "-"),
        "name": up.get("name", ""),
        "type": "armor",
        "rarity": "common",
        "attunement": False,
        "weight": str(up.get("weight", "")) + (" lb" if up.get("weight") else ""),
        "cost": str(up.get("cost", "")) or "",
        "desc": "",
        "properties": {
            "category": up.get("category", "") or "",
            "ac_base": up.get("base_ac", 0),
            "stealth_disadvantage": bool(up.get("stealth_disadvantage")),
        },
        "actions": [],
        "system": "dnd5e",
        "scope": "global",
        "source": "srd",
        "_attribution": ATTRIBUTION,
    }


# ── Type dispatch table ──────────────────────────────────────────────────────
# Maps the on-disk content directory → (Open5e endpoint, Pydantic model,
# transformer). Some Open5e endpoints (magicitems / weapons / armor) all
# write into the same ``items/`` directory.
ENDPOINTS: dict[str, list[tuple[str, type, callable]]] = {
    "spells":      [("spells",      Spell,      transform_spell)],
    "monsters":    [("monsters",    Monster,    transform_monster)],
    "feats":       [("feats",       Feat,       transform_feat)],
    "backgrounds": [("backgrounds", Background, transform_background)],
    "conditions":  [("conditions",  Condition,  transform_condition)],
    "items": [
        ("magicitems", Item, transform_magicitem),
        ("weapons",    Item, transform_weapon),
        ("armor",      Item, transform_armor),
    ],
}


# ── Pipeline ─────────────────────────────────────────────────────────────────
def write_record(record: dict, *, type_dir: str, model: type) -> tuple[bool, str]:
    """Validate then atomically write one record. Returns ``(ok, message)``."""
    slug = _sanitize_slug(record.get("slug") or "")
    if not slug:
        return False, f"invalid slug: {record.get('slug')!r}"
    # Update the record so the saved file shows the sanitized form.
    record["slug"] = slug
    try:
        validated = model.model_validate(record).model_dump(by_alias=True)
    except Exception as e:
        return False, f"validation failed: {e}"
    out_dir = DEST_ROOT / type_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    final = out_dir / f"{slug}.json"
    tmp = out_dir / f".{slug}.json.tmp"
    tmp.write_text(json.dumps(validated, indent=2, ensure_ascii=False), encoding="utf-8")
    os.replace(tmp, final)
    return True, str(final)


def _is_srd(upstream: dict) -> bool:
    """Open5e tags SRD records with document__slug == 'wotc-srd'. Some
    response shapes embed the document object instead — handle both."""
    doc_slug = upstream.get("document__slug")
    if not doc_slug:
        doc = upstream.get("document") or {}
        if isinstance(doc, dict):
            doc_slug = doc.get("slug")
    return (doc_slug or "").lower() == SRD_DOCUMENT_SLUG


def build(types: list[str], *, dry_run: bool, include_all: bool) -> dict[str, dict[str, int]]:
    summary: dict[str, dict[str, int]] = {}
    for type_dir in types:
        if type_dir not in ENDPOINTS:
            print(f"  skip unknown type: {type_dir}")
            continue
        summary[type_dir] = {"ok": 0, "skipped": 0, "filtered_non_srd": 0}
        for endpoint, model, transformer in ENDPOINTS[type_dir]:
            print(f"[{type_dir}] fetching {endpoint}...")
            try:
                raw = fetch_all(endpoint)
            except Exception as e:
                print(f"  FAIL: {e}")
                continue
            for up in raw:
                if not include_all and not _is_srd(up):
                    summary[type_dir]["filtered_non_srd"] += 1
                    continue
                record = transformer(up)
                if dry_run:
                    summary[type_dir]["ok"] += 1
                    continue
                ok, msg = write_record(record, type_dir=type_dir, model=model)
                if ok:
                    summary[type_dir]["ok"] += 1
                else:
                    summary[type_dir]["skipped"] += 1
                    print(f"  skip {up.get('slug','?')}: {msg}")
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--type",
        default=",".join(ENDPOINTS.keys()),
        help="comma-separated content types to build (default: all)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="fetch and transform, but don't write any files",
    )
    parser.add_argument(
        "--include-all",
        action="store_true",
        help="include every Open5e document, not just the WotC SRD baseline. "
        "Default is SRD-only because that's the licensing perimeter the rest "
        "of the codebase cites; only enable if you've verified the third-party "
        "licenses for your deployment.",
    )
    args = parser.parse_args()
    types = [t.strip() for t in args.type.split(",") if t.strip()]

    print(f"Open5e base : {OPEN5E_BASE}")
    print(f"Output root : {DEST_ROOT}")
    print(f"Types       : {types}")
    print(f"Dry-run     : {args.dry_run}")
    print(f"Scope       : {'ALL Open5e' if args.include_all else 'SRD only (document__slug=wotc-srd)'}\n")

    if not args.dry_run:
        print(
            "⚠  WARNING: writing to the live content dir OVERWRITES each file\n"
            "   wholesale. The shipped JSONs carry curated fields this script\n"
            "   does NOT regenerate (actions[].area, upcast, damage scaling,\n"
            "   action gating — see the module docstring). A blind re-run\n"
            "   silently drops them and breaks AoE placement + upcast tests.\n"
            "   Prefer --dry-run / a scratch DEST_ROOT + a hand-merged diff.\n"
        )

    summary = build(types, dry_run=args.dry_run, include_all=args.include_all)

    print("\n-- Summary -----------------------------------------")
    for type_dir, counts in summary.items():
        print(f"  {type_dir:<14} ok={counts['ok']:<5} "
              f"skipped={counts['skipped']:<3} "
              f"non-srd-filtered={counts['filtered_non_srd']}")
    print("----------------------------------------------------")
    return 0


if __name__ == "__main__":
    sys.exit(main())
